""EMOTION DETECTION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oiywAJF6g5u_eIEzn6G_NSY4pUDyBtd
"""

!pip install pysentimiento

from pysentimiento import create_analyzer

emotion = create_analyzer(task='emotion',lang = 'en')
result = emotion.predict('i love maths')
result.output

def emotion_detection(text):
    emotion = create_analyzer(task='emotion',lang = 'en')
    result = emotion.predict(text)
    return result.output
emotion_detection('i love maths')

emotion_detection('I am feeling very scared today!')

hatespeech = create_analyzer(task='hate_speech',lang = 'en')
result = hatespeech.predict('I hate maths')
next(iter(result.probas.items()),None)

def hatespeech_detection(text):
    hatespeech = create_analyzer(task='hate_speech',lang = 'en')
    result = hatespeech.predict(text)
    return next(iter(result.probas.items()),None)
    hatespeech_detection('I hate maths')

text = "I love spending time with the people who make me feel happy."

emotion = emotion_detection(text)
hatespeech = hatespeech_detection(text)



print(emotion)
print(hatespeech)
#
